### ISSUE TITLE
Record and stream to GBD

### ISSUE THREAD

**Issue by extremer** [generic-beat-detector/GBD#3]
Hi

Thanks to your solution,  I'm trying to build a system which records live sound and categorize signals(kick, snare, cymbals).
System works fine with a recorded wav files following your guide and now I'm trying to record.
Somehow it works using the following command

`arecord -f cd | aplay -D gbd --period-size 1024 -v`

The problem is latency. Is there any better solution you recommend to reduce latency?

Thank you.

**Comment by generic-beat-detector** [comment]
Hello extremer,

Pardon the delay in response. 

What is your capture setup? Line-in?

Regards,
GBD

**Comment by extremer** [comment]
Hi there,
Now, we are capturing audio with 2Mic Hat.

**Comment by generic-beat-detector** [comment]
Is the objective simply low-latency capture and analysis of beats?
Or is realtime playback of the captured PCM also required?

If the objective is simply capture-and-analyze then a basic ALSA
capture program could be written which then and sends 1024 
ALSA stereo frames (@ ALSA period) directly to the GBD server 
via direct API calls, e.g. as used by gbdclient.c. In this case, the 
latency will be 23ms which is the same as that incurred for GBD 
playback setups.

Note that theoretically, "arecord -D gbd -f cd --period-size 1024 -v" should 
also work since the setup is in effect an ALSA/LADSPA configuration. 
However, while the ALSA PCM plugin mechanism will route the captured
PCM signals in the reverse PCM plugin order (i.e. from H/W to the 
application), and even report 1024 ALSA frames and 44100Hz at the 
gbdclient stage (i.e.  as displayed by the "-v" switch), it doesn't seem to
guarantee a PCM stream with fixed 1024 ALSA frames @ ALSA period.

Does this help?
GBD.

**Comment by generic-beat-detector** [comment]
Hello again,

Is this, 

    https://www.seeedstudio.com/ReSpeaker-2-Mics-Pi-HAT-p-2874.html

the RPi Hat addon being used? 

If so, just bear in mind that since GBD is a generic beat detector whose calibration is
optimized for CD quality sound, capture via a commodity on-board mic is unlikely to 
produce impressive results. For best results, low-latency capture should be via line-in;
with the remote source of sound producing near studio quality PCM.

Regards,
GBD.

**Comment by extremer** [comment]
Thank you.
I'm planning on attaching audio interface that can accept line in from audio console.(Apogee Jam)
Hopefully each drum sound can be recorded directly with their own mics and mixed with console to extract isolated snare, kick, cymbal signals.
